version: "3.9"
services:
  api:
    build: ./api
    ports: 
    - "5000:5000"
    volumes: 
    - ./api:/app
    environment: 
        FLASK_ENV: build
  
  front:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./front:/app
    depends_on: 
      - api